tasktracker/lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  def get_current_user(conn, _params) do
    #move this fn out of the router module
    user_id = get_session(conn, :user_id)
    user = Tasktracker.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  scope "/", TasktrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/tasks", TaskController
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
    get "/taskfeed", PageController, :feed
    get "/alltasks", PageController, :alltasks
  end

  # Other scopes may use custom stacks.
  # scope "/api", TasktrackerWeb do
  #   pipe_through :api
  # end
end

tasktracker/lib/tasktracker_web/views/layout_view.ex
defmodule TasktrackerWeb.LayoutView do
  use TasktrackerWeb, :view
end

tasktracker/lib/tasktracker_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Task Tracker App!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="row">
      <div class="col-3 offset-8">
        <%= if @current_user do %>
          <p>
          Logged in as: <%= @current_user.name %> |
          <%= link "Log Out", to: "/session", method: :delete %>
        </div>
        <div class= "col-4 offset-6" align="center">
          <div class="usr-feature">
            <%= link "New Task", to: task_path(@conn, :new), class: "btn btn-primary" %>
            <%= link "View All Tasks", to: page_path(@conn, :alltasks), class: "btn btn-primary" %>
            <%= link "My Task Feed", to: page_path(@conn, :feed), class: "btn btn-primary" %>
            <%= link "Edit Profile", to: user_path(@conn, :edit, @current_user), class: "btn btn-warning" %>
            <br>
          </div>
        </p>
        <% else %>
          <p>Not logged in.</p>
        <% end %>
      </div>
    </div>
    <div class="container">
      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>